linters-settings:
  gofmt:
    simplify: true
  misspell:
    locale: US
  govet:
    disable:
      - shadow
      - nilness
    enable-all: true

linters:
  enable:
    - gofmt
    - revive
    - misspell
    - govet
    - unused
    - errcheck
    - copyloopvar
    - gosimple
    - ineffassign
    - staticcheck
    - whitespace
    - bodyclose
    - inamedparam
  disable-all: false
  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - should have a package comment
    - exported (.+) should have comment( \(or a comment on this block\))? or be unexported
  exclude-dirs:
    - .github
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - path: _test\.go
      linters:
        - govet
      text: "fieldalignment"
