run:
  go: "1.19"
  skip-dirs:
    - .github

linters-settings:
  gofmt:
    simplify: true
  misspell:
    locale: US
  govet:
    disable:
      - shadow
      - nilness
    enable-all: true

linters:
  enable:
    - gofmt
    - revive
    - misspell
    - govet
    - unused
    - errcheck
    - exportloopref
  disable-all: false
  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - should have a package comment
    - exported (.+) should have comment( \(or a comment on this block\))? or be unexported
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - path: _test\.go
      linters:
        - govet
      text: "fieldalignment"
